services:
  frontend:
    image: ghcr.io/pickle-time/pickletime-frontend:latest
    container_name: frontend
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    env_file:
     - .env
    command: ["npm", "run", "preview"]