# For development
services:
  frontend:
    image: ghcr.io/pickle-time/pickletime-frontend:latest
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
     - .env
    command: ["npm", "run", "preview"]

  frontend-nginx:
    container_name: frontend-nginx
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    env_file:
    - .env