name: Build and Test

on:
  push:
    branches:
      - ['**']
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    container:
      image: node:20-alpine

    steps:
      - name: Install git # Required for actions/checkout in Alpine Image
        run: apk add --no-cache git

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Enforce code styles
        run: npm run lint

      - name: Run tests
        run: npm run test
