name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: node:20-slim

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        run: mkdir -p ~/.npm
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-


      - name: Install dependencies
        run: npm ci

      - name: Enforce code styles
        run: npm run lint

      - name: Run tests
        run: npm run test
