name: Test, Build, and Publish Image

on:
  push:
    branches:
      - main
      - 11-add-ssh-pull-container-step-to-github-actions-workflow
  workflow_dispatch:

jobs:
  test:
    uses: PickLe-Time/pickletime-frontend/.github/workflows/test.yml@main

  build-publish:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/pickle-time/pickletime-frontend:latest

    deploy:
      needs: build-publish
      runs-on: ubuntu-latest

      steps:
        - name: Deploy to production via SSH
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER}}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd /home/opc/projects/pickletime/pickletime-infra
              docker compose -f docker-compose.prod.yml pull
              docker compose -f docker-compose.prod.yml up -d --remove-orphans
          